name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '* $TITLE (#$NUMBER) by @$AUTHOR'
template: |
  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: '⭐️ Public API changes'
    label: 'breaking'
  - title: '💫 Features'
    labels:
      - 'feature'
      - 'breaking'
  - title: '🛠️ Bug fixes'
    label: 'bug'
  - title: '🕹️ Others'
    label: 'chore'

version-resolver:
  # Major is not meant to be used at the moment.
  # Should be used with type: breaking in the future.
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'breaking'
      - 'feature'
      - 'chore'
  patch:
    labels:
      - 'bug'

exclude-labels:
  - 'skip-changelog'

autolabeler:
  - label: 'chore'
    title:
      - '/chore/i'
  - label: 'bug'
    title:
      - '/fix/i'
  - label: 'feature'
    title:
      - '/feat/i'
  - label: 'breaking'
    title:
      - '/breaking/i'
